### ISSUE TITLE
Info-registers switches buffers

### ISSUE THREAD

**Issue by eko234** [Delapouite/kakoune-registers#3]
I'm using Kakoune v2020.09.01, your plugins are really cool i use a handful of, the issue I'm having is that whenever i use the command info-registers it makes me jump to the registers buffer instead of just showing the info box, which is the intended behavior if i understand well, i think it might have something to do with the part that actually writes to the buffer, hope you can help me out, thanks.

**Comment by JonathanSchaber** [comment]
The problem seems to be that the registers-buffer created by `list-registers` used for populating the info-box is not being deleted afterwards.

Updating the `info-registers` command the following way should work out:

    define-command info-registers -docstring 'populate an info box with the content of registers' %{
        list-registers
        try %{ execute-keys '%<a-s>s^.{30}\K[^\n]*<ret>c…<esc>' }
        execute-keys '%'
        declare-option -hidden str-list reg_info %val{selection}
        execute-keys ':bd<ret>'
        info -title registers -- %opt{reg_info}
    }

**Comment by forbesmyester** [comment]
It does seem to leave you on the `*registers*` buffer. I have @JonathanSchaber 's code in my kakrc as `show-registers` which seems to fix the problem

**Comment by eko234** [comment]
> 
> 
> It does seem to leave you on the `*registers*` buffer. I have @JonathanSchaber 's code in my kakrc as `show-registers` which seems to fix the problem

thanks, I'm gonna give it a try.

**Comment by forbesmyester** [comment]
Think we should reopen this so other people have the solution...
